### ISSUE TITLE
Big Sur icon 

### ISSUE THREAD

**Issue by sealvessel** [marcocebrian/kagisearchsafari#1]
Icon
[KagiSearch.icns.zip](https://github.com/marcocebrian/kagisearchsafari/files/7492688/KagiSearch.icns.zip)

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/66351949/140653875-e53acd77-f951-4246-a64d-bc29932bd202.png">
Here is a preview, download the zip for the .icns version.

**Comment by marcocebrian** [comment]
Thank you so much @sealvessel
