### ISSUE TITLE
Doesn't add Kagi to default search

### ISSUE THREAD

**Issue by Tarang** [marcocebrian/kagisearchsafari#4]
I installed the latest 1.2 release but I think something might be wrong. It doesn't add Kagi to the search list.

<img width="250" alt="image" src="https://user-images.githubusercontent.com/1616628/163884027-4e81a39d-f7ae-4140-af8e-da8229a6c2f9.png">

I tried to add Kagi to the list as well but can see the previous code has been yanked (in https://github.com/marcocebrian/kagisearchsafari/commit/7b254b661b38aae97cde5ba6d6e2a0475a5ea554). I'm not sure if there's some other source for the correct files but I could make a PR to fix.

**Comment by marcocebrian** [comment]
It just works. You don't need to add or remove anything. In any case, in the current scenario I recommend you to install the complete Safari extension from: https://apps.apple.com/in/app/custom-search-engine/id1588019370?mt=12
