### ISSUE TITLE
Kagi Full fledged extension for Safari not available in your region

### ISSUE THREAD

**Issue by ctrlok** [marcocebrian/kagisearchsafari#6]
Hi. 
I'm from Ukraine, and I want to check/install the paid extension, but it's not available in our regional App Store. Is this something that can be fixed? Thanks!

**Comment by marcocebrian** [comment]
Dear Seva, Soon i will make it available outside the app Store as apple has changed the guidelines and doesn't allow to substitute the default search engine in safari.Just around one week.Sent from my iPhone14:23, 27 de abril de 2022, Seva Poliakov ***@***.***>:
Hi.
I'm from Ukraine, and I want to check/install the paid extension, but it's not available in our regional App Store. Is this something that can be fixed? Thanks!

**Comment by marcocebrian** [comment]
Available now!

https://apps.apple.com/in/app/custom-search-engine/id1588019370?mt=12
